/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  searchPlaceholder: 'Search {0}',
  searchByNamePlaceholder: 'Search by name',
  searchIconTooltip: 'Search by {0}',
  searchClearIconTooltip: 'Clear',
  collapseSearch: 'Close search',
  selectAll: 'Select all items',
  selectAllAria: 'Select all items',
  selectItem: 'Select {0}',
  selectItemAria: 'Select {0}. When selected an action bar of options can be reached per shift-tab',
  selectedItemActionBarAria: 'Action bar of selected items',
  nameAria: '{0}',
  nameNoOpenAria: '{0}. Can not be opened.',
  NodeTableNoItems: "No results found.",
  NodeTableLoadingItems: "Loading...",
  NodeTableProcessingItems: "",
  NodeTablePageInfo: "Showing _START_ to _END_ of _TOTAL_ items",
  NodeTableEmptyPageInfo: "Showing 0 items",
  NodeTableFilteredPageInfo: "(filtered from _MAX_ total items)",
  NodeTablePageInfoSuffix: "",
  NodeTablePageThousandsSeparator: ",",
  NodeTablePagingFirst: "First",
  NodeTablePagingLast: "Last",
  NodeTablePagingPrevious: "Previous",
  NodeTablePagingNext: "Next",
  NodeTablePageSizeSelector: "Show _MENU_ items",
  NodeTablePageFilterLabel: "Filter by:",
  NodeTableSortAscending: ": Click to sort ascending",
  NodeTableSortDescending: ": Click to sort descending",
  NodeTableSortByAria: '{0}: Click to sort by {0}',
  backButtonTooltip: 'Go back',
  typeAndNameAria: '{0} {1}', // MSWord document report12.doc
  tableApplicationAria: 'Table',
  descriptionColumnTitle: 'Description',
  cellNoTexAria: 'No text'
});
