/* Copyright (c) 2016-2017  OpenText Corp. All Rights Reserved. */

define({
  months: ["January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"],
  dialogTitle: 'Workflow Tracking',
  emptyListText: 'There are no items to display',
  totalMsg: 'Total',
  onTime: 'On time',
  completed: 'Completed',
  late: 'Late',
  expandLabel: 'Expand',
  dueDateLabel: 'Due date',
  currentStepNameLabel: 'Current step',
  assignedToLabel: 'Assigned to',
  startDateLabel: 'Start date',
  startedLabel: 'Started',
  statusLabel:'Status',
  initiatorLabel:'Initiator',
  wfNameLabel: 'Workflow name',
  NameLabel:'Name',
  allFilterLabel: 'All',
  completedFilterLabel: 'Completed',
  lateFilterLabel: 'Late',
  ontimeFilterLabel: 'On Time',
  headerFilterTitle: 'Refine by',
  headerFilterLabel: 'Show items with status',
  days: 'days',
  day: 'day',
  dueInLabel: 'due in',
  dueLabel: 'due',
  todayLabel: 'today',
  details:'Details',
  attachments:'Attachments',
  startLabel: 'Start',
  endLabel: 'End',
  currentStepLabel: 'Current Step',
  nextStepLabel: 'Next Step',
  completedStepLabel: 'Completed Step',
  currentStepsLabel: 'Current Steps',
  completedStepsLabel: 'Completed Steps'
});
